// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chevron-down': string;
  'dropdown': string;
  'dropdown-menu': string;
  'dropdown-menu-title': string;
  'dropdown-option': string;
  'dropdown-selected': string;
  'fades-in-out': string;
  'hide': string;
  'modal': string;
  'modal-chevron-down': string;
  'modal-dropdown-list': string;
  'modal-dropdown-selected': string;
  'modal-option': string;
  'scroll': string;
  'selected': string;
  'visible': string;
}
declare var cssExports: CssExports;
export = cssExports;
