// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fades-in-out': string;
  'menu-item': string;
  'menu-item--active': string;
  'menu-item__left': string;
  'menu-item__left__text': string;
  'menu-item__right': string;
  'nested': string;
}
declare var cssExports: CssExports;
export = cssExports;
