// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropdown-menu': string;
  'dropdown-menu__bottom': string;
  'dropdown-menu__top': string;
  'dropdown-menu__top-close': string;
  'dropdown-menu__top-open': string;
  'dropdown-menu__top-open--divider': string;
  'fades-in-out': string;
}
declare var cssExports: CssExports;
export = cssExports;
