// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'browse-button': string;
  'content-description': string;
  'content-header': string;
  'fades-in-out': string;
  'modal': string;
  'modal-box': string;
  'modal-container': string;
  'modal-container--bordered': string;
  'modal-hide': string;
  'modal-icon-close': string;
  'modal-main-content': string;
  'modal-visible': string;
}
declare var cssExports: CssExports;
export = cssExports;
