// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'available': string;
  'coming-soon': string;
  'fades-in-out': string;
  'unavailable': string;
}
declare var cssExports: CssExports;
export = cssExports;
