// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'brand': string;
  'brand__name': string;
  'fades-in-out': string;
}
declare var cssExports: CssExports;
export = cssExports;
