// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bordered': string;
  'button': string;
  'button--danger': string;
  'button--disabled': string;
  'button--plain': string;
  'button--round': string;
  'button--square': string;
  'button--standard': string;
  'button--warning': string;
  'button--white': string;
  'fades-in-out': string;
  'inverted': string;
  'ripple': string;
}
declare var cssExports: CssExports;
export = cssExports;
