// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'dot': string;
  'dot--dark': string;
  'fades-in-out': string;
}
declare var cssExports: CssExports;
export = cssExports;
