# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  unit-tests:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

orbs:
  aws-ecr: circleci/aws-ecr@3.1.0

workflows:
  version: 2
  branch:
    jobs:
      - unit-tests
      - aws-ecr/build_and_push_image:
          name: build-image-staging
          context: AWS Keys Prod
          repo: core-admin-ui
          tag: test
          requires:
            - unit-tests
          filters:
            branches:
              only: develop
      - aws-ecr/build_and_push_image:
          name: build-image-master
          context: AWS Keys Prod
          repo: core-admin-ui
          tag: latest
          requires:
            - unit-tests
          filters:
            branches:
              only: master
