# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  unit-tests:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

orbs:
  aws-ecr: circleci/aws-ecr@3.1.0
  aws-eks: circleci/aws-eks@0.2.2

workflows:
  branch:
    jobs:
      - unit-tests
      - aws-ecr/build_and_push_image:
          name: build-image-staging
          context: AWS Keys Prod
          repo: core-admin-ui
          tag: test
          requires:
            - unit-tests
          # filters:
          #   branches:
          #     only: develop
      - aws-ecr/build_and_push_image:
          name: build-image-master
          context: AWS Keys Prod
          repo: core-admin-ui
          tag: latest
          requires:
            - unit-tests
          filters:
            branches:
              only: master
      - aws-eks/update-container-image:
          name: deploy-admin-ui-staging
          cluster-name: core-staging-cluster
          # container-image-updates: 'admin-ui=nginx:1.9.1'
          post-steps:
            - kubernetes/delete-resource:
                resource-names: admin-ui
                resource-types: deployment
                wait: true
          record: true
          resource-name: deployment/admin-ui
          # filters:
          #   branches:
          #     only: develop
