# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:

  unit-tests:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test
    
  deploy-staging:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
    
  deploy-prod:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install


workflows:
  version: 2

  pr-tests:
    jobs:
      - unit-tests:
          filters:
            branches:
              only: /pull\/.*/

  test-and-deploy-staging:
    jobs:
      - unit-tests:
          filters:
            branches:
              only: develop
      - deploy-staging:
          requires:
            - unit-tests
          filters:
            branches:
              only: develop

  test-and-deploy-prod:
    jobs:
      - unit-tests:
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - unit-tests
          filters:
            branches:
              only: master
