// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bare-tile': string;
  'fades-in-out': string;
  'lighter-tile': string;
}
declare var cssExports: CssExports;
export = cssExports;
