// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'black': string;
  'blue': string;
  'fades-in-out': string;
  'loading-ring': string;
}
declare var cssExports: CssExports;
export = cssExports;
