// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkmark-label': string;
  'dark': string;
  'error': string;
  'error-message': string;
  'fades-in-out': string;
  'input-base': string;
  'input-date': string;
  'input-email': string;
  'input-file': string;
  'input-group': string;
  'input-image': string;
  'input-label': string;
  'input-number': string;
  'input-password': string;
  'input-tel': string;
  'input-text': string;
  'input-url': string;
  'password-visibility-indicator': string;
}
declare var cssExports: CssExports;
export = cssExports;
