// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'container--closable': string;
  'container--hide': string;
  'fades-in-out': string;
  'icon': string;
  'icon--close': string;
  'sub-title': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
