// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fades-in-out': string;
  'header': string;
  'header-no-icon': string;
  'hide': string;
  'modal': string;
  'modal--dark-gray': string;
  'modal--gray': string;
  'modal--white': string;
  'modal-body': string;
  'modal-container': string;
  'modal-content': string;
  'modal-footer': string;
  'modal-icon': string;
  'modal-icon-close': string;
  'modal-plain': string;
  'modal-sub-title': string;
  'modal-title': string;
  'no-pointer': string;
  'plain-modal-header': string;
  'scroll': string;
  'visible': string;
}
declare var cssExports: CssExports;
export = cssExports;
