// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'box-container': string;
  'button-group': string;
  'cancel-button-container': string;
  'fades-in-out': string;
  'main-container': string;
  'save-button-container': string;
  'save-button-container--disabled': string;
  'title': string;
}
declare var cssExports: CssExports;
export = cssExports;
