// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fades-in-out': string;
  'side-menu': string;
  'visible': string;
}
declare var cssExports: CssExports;
export = cssExports;
