// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'error': string;
  'fades-in-out': string;
  'fakebox': string;
  'validation-label': string;
}
declare var cssExports: CssExports;
export = cssExports;
