// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn-container': string;
  'btn-disabled': string;
  'column-2': string;
  'fades-in-out': string;
  'form-container': string;
  'input-validation-message-label': string;
}
declare var cssExports: CssExports;
export = cssExports;
