// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bottom': string;
  'bottom-left': string;
  'bottom-right': string;
  'button': string;
  'canvas': string;
  'container': string;
  'fades-in-out': string;
  'hide': string;
  'markers': string;
  'markers-ctn': string;
  'top': string;
  'top-left': string;
  'top-right': string;
  'video': string;
}
declare var cssExports: CssExports;
export = cssExports;
